name: mockito_code_generator
description: Mockito Code Generator is a code generator for https://pub.dev/packages/mockito package.
version: 0.1.0
author: adson.leal <adsonpleal@gmail.com>
homepage: https://github.com/adsonpleal/mockito-code-generator


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  build: ^1.0.0
  analyzer: '>= 0.32.4 <=0.38.2'
  source_gen: ^0.9.0
